//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExchangGifts
    {
        public int EG_ID { get; set; }
        public Nullable<int> S_ID { get; set; }
        public string EG_GiftCode { get; set; }
        public string EG_GiftName { get; set; }
        public string EG_Photo { get; set; }
        public Nullable<int> EG_Point { get; set; }
        public Nullable<int> EG_Number { get; set; }
        public Nullable<int> EG_ExchangNum { get; set; }
        public string EG_Remark { get; set; }
    
        public virtual Shops Shops { get; set; }
    }
}
