//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class exchanglogs
    {
        public int EL_ID { get; set; }
        public Nullable<int> S_ID { get; set; }
        public Nullable<int> U_ID { get; set; }
        public Nullable<int> MC_ID { get; set; }
        public string MC_CardID { get; set; }
        public string MC_Name { get; set; }
        public Nullable<int> EG_ID { get; set; }
        public string EG_GiftCode { get; set; }
        public string EG_GiftName { get; set; }
        public Nullable<int> EL_Number { get; set; }
        public Nullable<int> EL_Point { get; set; }
        public Nullable<System.DateTime> EL_CreateTime { get; set; }
    
        public virtual shops shops { get; set; }
        public virtual users users { get; set; }
    }
}
