//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBEntities : DbContext
    {
        public DBEntities()
            : base("name=DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cardlevels> cardlevels { get; set; }
        public virtual DbSet<categories> categories { get; set; }
        public virtual DbSet<categoryitems> categoryitems { get; set; }
        public virtual DbSet<consumeorders> consumeorders { get; set; }
        public virtual DbSet<exchanggifts> exchanggifts { get; set; }
        public virtual DbSet<exchanglogs> exchanglogs { get; set; }
        public virtual DbSet<memcards> memcards { get; set; }
        public virtual DbSet<shops> shops { get; set; }
        public virtual DbSet<syslogs> syslogs { get; set; }
        public virtual DbSet<transferlogs> transferlogs { get; set; }
        public virtual DbSet<users> users { get; set; }
    }
}
