//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UPMSEntities : DbContext
    {
        public UPMSEntities()
            : base("name=UPMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CardLevels> CardLevels { get; set; }
        public virtual DbSet<Categories> Categories { get; set; }
        public virtual DbSet<CategoryItems> CategoryItems { get; set; }
        public virtual DbSet<ConsumeOrders> ConsumeOrders { get; set; }
        public virtual DbSet<ExchangGifts> ExchangGifts { get; set; }
        public virtual DbSet<ExchangLogs> ExchangLogs { get; set; }
        public virtual DbSet<MemCards> MemCards { get; set; }
        public virtual DbSet<Shops> Shops { get; set; }
        public virtual DbSet<SysLogs> SysLogs { get; set; }
        public virtual DbSet<TransferLogs> TransferLogs { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
