//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class shops
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public shops()
        {
            this.consumeorders = new HashSet<consumeorders>();
            this.exchanggifts = new HashSet<exchanggifts>();
            this.exchanglogs = new HashSet<exchanglogs>();
            this.memcards = new HashSet<memcards>();
            this.transferlogs = new HashSet<transferlogs>();
            this.users = new HashSet<users>();
        }
    
        public int S_ID { get; set; }
        public string S_Name { get; set; }
        public Nullable<int> S_Category { get; set; }
        public string S_ContactName { get; set; }
        public string S_ContactTel { get; set; }
        public string S_Address { get; set; }
        public string S_Remark { get; set; }
        public Nullable<sbyte> S_IsHasSetAdmin { get; set; }
        public Nullable<System.DateTime> S_CreateTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<consumeorders> consumeorders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<exchanggifts> exchanggifts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<exchanglogs> exchanglogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<memcards> memcards { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<transferlogs> transferlogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<users> users { get; set; }
    }
}
