//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysLogs
    {
        public int SL_ID { get; set; }
        public Nullable<int> U_ID { get; set; }
        public string SL_Module { get; set; }
        public string SL_Details { get; set; }
        public Nullable<System.DateTime> SL_CreateTime { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
